name: kakaomap_with_ai
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kakaomap_webview: ^0.6.2
  webview_flutter: ^3.0.4
  http: ^0.13.3
  firebase_core: ^2.10.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.10.0 # 버전을 확인하고 최신 버전으로 설정
  google_maps_flutter: ^2.2.0
  url_launcher: ^6.1.10  # 최신 버전으로 업데이트할 수 있습니다
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  flutter_map: ^4.0.0
  share: ^2.0.4 
  share_plus: ^10.0.0 
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0
  geolocator_web: ^2.1.7
  flutter_inappwebview: ^5.3.2
  geolocator: ^9.0.2
  geocoding: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - .env
    - assets/AI.png
    - assets/강남구.geojson
    - assets/강동구.geojson
    - assets/강북구.geojson
    - assets/강서구.geojson
    - assets/관악구.geojson
    - assets/광진구.geojson
    - assets/구로구.geojson
    - assets/금천구.geojson
    - assets/노원구.geojson
    - assets/도봉구.geojson
    - assets/동대문구.geojson
    - assets/동작구.geojson
    - assets/마포구.geojson
    - assets/서대문구.geojson
    - assets/서초구.geojson
    - assets/성동구.geojson
    - assets/성북구.geojson
    - assets/송파구.geojson
    - assets/양천구.geojson
    - assets/영등포구.geojson
    - assets/용산구.geojson
    - assets/은평구.geojson
    - assets/종로구.geojson
    - assets/중구.geojson
    - assets/중랑구.geojson
    - assets/planning.gif
    - assets/mapping.gif
    - assets/saving.gif
    - assets/checking.gif
    - assets/planai.gif
    - assets/loading.gif

  fonts:
    - family: Cafe24Supermagic
      fonts:
        - asset: assets/fonts/Cafe24Supermagic-Regular-v1.0.otf
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/static/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/static/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/NotoSansKR-Regular.ttf
          weight: 400
